######################### default configuration ###############################
baseURL = "https://dealicia2.netlify.app/"
title = "Tienda de repostería en la costa del Sol | d'Alicia • Delicias y Caprichos"
theme = "biztrox-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "biztrox" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = "en" # disable language from here
DefaultContentLanguage = "es"


############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick-theme.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/animate/animate.css"
  [[params.plugins.css]]
  URL = "https://cdn.snipcart.com/themes/v3.0.17/default/snipcart.css"


  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


#################################### navigation ##################################
[menu]

### English ###

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Shop"
  URL = "shop"
  weight = 2

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

 [[menu.main]]
 weight = 5
 name = "Pages"
 hasChildren = true

   [[menu.main]]
   parent = "Pages"
   name = "product"
   URL = "product"

  # footer menu
  [[menu.footer]]
  name = "Legal"
  URL = "#"
  weight = 1

  [[menu.footer]]
  name = "Sitemap"
  URL = "#"
  weight = 2

  [[menu.footer]]
  name = "Privacy Policy"
  URL = "#"
  weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "#"
  weight = 4

  ### Spanish ###
  [[Languages.es.menu.main]]
  name = "Conócenos"
  URL = "about"
  weight = 1

  [[Languages.es.menu.main]]
  name = "Tienda"
  URL = "shop"
  weight = 2

  [[Languages.es.menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3

  [[Languages.es.menu.main]]
  name = "Contacto"
  URL = "contact"
  weight = 4

  [[Languages.es.menu.footer]]
  name = "Aviso Legal"
  URL = "legal/avisolegal"
  weight = 1

  [[Languages.es.menu.footer]]
  name = "Política de Privacidad"
  URL = "legal/politica_privacidad"
  weight = 2

  [[Languages.es.menu.footer]]
  name = "Política de Cookies"
  URL = "legal/politica_cookies"
  weight = 3

  [[Languages.es.menu.footer]]
  name = "Condiciones de Compra"
  URL = "legal/condiciones_compra"
  weight = 4


########################### default parameters #################################
[params]
logo = "images/logo.png"
logo_white = "images/logo-footer.png"
mail = "hola@dealicia.com"
mobile = "952 92 71 99"
# Meta data
description = "d'Alicia • Delicias y Caprichos"
author = "normal media"
# contact form
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"

# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# snipcart public api key
snipcartAPI = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
currency = "€"

# nav Button
[params.nav_button]
enable = false
link = "contact"

# preloader?
[params.preloader]
enable = false
preloader = "images/preloader.gif"

############################ Contact information ############################
[[params.contacts]]
icon = "ti-mobile"

  [[params.contacts.contact]]
  contact_item = "+88 0123 456 789"

  [[params.contacts.contact]]
  contact_item = "+88 987 654 3210"

[[params.contacts]]
icon = "ti-email"

  [[params.contacts.contact]]
  contact_item = "hola@dealicia.com"

[[params.contacts]]
icon = "ti-map-alt"

  [[params.contacts.contact]]
  contact_item = "24/B Garden Street. <br> Northambia, Weals, UK"

############################ google map #####################################
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################ client logo slider #############################
[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-1.png"
link = "#"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-2.png"
link = "https://examplesite.com"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-3.png"
link = "#"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-4.png"
link = "https://examplesite.com"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-5.png"
link = "#"

[[params.clients_logo_slider]]
logo = "images/client-logo/client-logo-3.png"
link = "https://examplesite.com"

########################### social icon #####################################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"


[Languages]

  ################################### English language #####################################
  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content/english"
  weight = 2
  home = "Home"

  # footer
  [Languages.en.params.footer]
  content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim."

  # subscribe
  subscribe = "Subscribe Us"
  subscribe_content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."

  # copyright
  copyright = "Copyright &copy; 2020 d'Alicia & site made by [normal](https://normalmedia.com)"



################################ Spanish language ################################
  [Languages.es]
  languageName = "Es"
  languageCode = "es-ES"
  contentDir = "content/spanish"
  weight = 1
  home = "Home"

  # footer
  [Languages.es.params.footer]
  content = "Repostería artesanal a partir de recetas tradicionales y exclusivas."

  # subscribe
  subscribe = "Suscribete"
  subscribe_content = "Lorem ipsum dolore sit amet, consect etur adipisicing. elit sed do eiusmod."

  # copyright
  copyright = "Copyright &copy; 2020 d'Alicia • web creada por [normal](https://normalmedia.com)"
