[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "repo"

[[redirects]]
  from = "/cafeterias-guadalmina-sotogrande-elpilar-marbella"
  to = "/"
  status = 301
  force = true
  query = {path = ":path"}

[redirects]
  from = "/tienda-online-reposteria"
  to = "/product"
  status = 301
  force = true
  query = {path = ":path"}
